name: '${project.name}'
version: '${project.version}'
main: pl.ynfuien.ychatmanager.YChatManager
api-version: 1.19
softdepend: [ PlaceholderAPI, Vault, LuckPerms ]
author: Ynfuien
description: '${project.description}'
website: '${project.url}'

commands:
  ychatmanager:
    aliases: [ycm]
    description: Plugin's main command
    permission: ychatmanager.command.main

  clearchat:
    aliases: [cc]
    description: Clears chat
    permission: ychatmanager.command.clearchat

  message:
    aliases: [msg, pm, tell]
    description: Sends private message to a player
    permission: ychatmanager.command.message

  reply:
    aliases: [r]
    description: Replies last messaged player
    permission: ychatmanager.command.reply

  nick:
    description: Sets custom nickname
    permission: ychatmanager.command.nick

permissions:
  ychatmanager.command.main:
    default: op
    children:
      reload: true
      help: true
      version: true
      anti-swear: true
      anti-swear.words: true
      anti-swear.exceptions: true
  ychatmanager.command.clearchat:
    default: op
  ychatmanager.command.message:
    default: true
    children:
      vanished: false
  ychatmanager.command.reply:
    default: true
  ychatmanager.socialspy:
    default: op
  ychatmanager.command.nick:
    default: op
    children:
      others: true
      unsafe: true
      custom: true